"""Trends data models for historical category/topic scoring and evidence traceability."""

from sqlalchemy import Column, String, DateTime, Date, Float, Integer, ForeignKey, Index, Text, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from trend_scout_enterprise.core.database import Base


class TopicTrendPoint(Base):
    """Pre-aggregated trend data point for a category or topic.

    Each row represents one time bucket (day/week/month) for a given topic/category,
    storing the average scores and a pointer to supporting evidence.
    """

    __tablename__ = "topic_trend_points"

    id = Column(String(36), primary_key=True)
    workspace_id = Column(String(36), ForeignKey("workspaces.id"), nullable=True, index=True)
    category = Column(String(100), nullable=False, index=True)
    topic_key = Column(String(255), nullable=False, index=True)
    # day/week/month bucket
    date_bucket = Column(Date, nullable=False, index=True)
    granularity = Column(String(20), nullable=False, default="day")  # day|week|month

    item_count = Column(Integer, default=0)
    avg_overall_score = Column(Float)
    avg_signal_strength = Column(Float)
    avg_cross_domain_impact = Column(Float)
    avg_investment_velocity = Column(Float)
    avg_technical_feasibility = Column(Float)
    avg_strategic_fit = Column(Float)

    # Human-readable summary generated by LLM or derived from top items
    summary = Column(Text)
    # List of source IDs that contributed items in this bucket
    source_ids = Column(JSON, default=list)

    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

    workspace = relationship("Workspace")
    evidence = relationship(
        "TrendEvidence",
        back_populates="trend_point",
        cascade="all, delete-orphan",
        order_by="TrendEvidence.rank",
    )

    __table_args__ = (
        Index(
            "ix_topic_trend_workspace_cat_topic_date",
            "workspace_id", "category", "topic_key", "date_bucket",
            unique=True,
        ),
    )


class TrendEvidence(Base):
    """Evidence linking a trend point back to the original RawItem and scoring rationale.

    Each row captures one top-contributing item for a given trend point, including
    the item score, the raw source, and the LLM/generated reasoning summary.
    """

    __tablename__ = "trend_evidence"

    id = Column(String(36), primary_key=True)
    trend_point_id = Column(String(36), ForeignKey("topic_trend_points.id"), nullable=False, index=True)
    raw_item_id = Column(String(36), ForeignKey("raw_items.id"), nullable=False, index=True)
    source_id = Column(String(36), ForeignKey("sources.id"), nullable=False, index=True)
    rank = Column(Integer, default=0)  # 1 = highest contributor
    overall_score = Column(Float)
    # Per-dimension scores at the time of aggregation
    dimension_scores = Column(JSON, default=dict)
    # LLM/generated rationale explaining why this item supports the trend conclusion
    rationale = Column(Text)

    trend_point = relationship("TopicTrendPoint", back_populates="evidence")
    raw_item = relationship("RawItem")
    source = relationship("Source")

    __table_args__ = (
        Index("ix_trend_evidence_trend_point_rank", "trend_point_id", "rank"),
    )
